{% set name = "konnektor" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 87aceb735c6407c0157576e1f23e45e050fb2f876a8b4d06e0674125af900c88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - versioningit
    - pip
  run:
    - python >={{ python_min }}
    - gufe >=1,<2
    - numpy
    - rdkit
    - networkx
    - scikit-mol <0.4.4
    - scikit-learn
    - ipycytoscape

test:
  imports:
    - konnektor
  commands:
    - pytest --pyargs konnektor
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/OpenFreeEnergy/konnektor
  summary: Konnektor is a package for calculating networks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - atravitz
    - mikemhenry
    - IAlibay
    - RiesBen
